# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = ALT, return, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = ALT SHIFT, q, Close active window, killactive

bindd = ALT, H, Move focus left, movefocus, l
bindd = ALT, L, Move focus right, movefocus, r
bindd = ALT, K, Move focus up, movefocus, u
bindd = ALT, J, Move focus down, movefocus, d

bindd = ALT, Q, Switch to workspace 1, workspace, 1
bindd = ALT, W, Switch to workspace 2, workspace, 2
bindd = ALT, E, Switch to workspace 3, workspace, 3
bindd = ALT, R, Switch to workspace 4, workspace, 4
bindd = ALT, T, Switch to workspace 5, workspace, 5

bindd = ALT SHIFT, Z, Move window to workspace 1, movetoworkspace, 1
bindd = ALT SHIFT, X, Move window to workspace 2, movetoworkspace, 2
bindd = ALT SHIFT, C, Move window to workspace 3, movetoworkspace, 3
bindd = ALT SHIFT, V, Move window to workspace 4, movetoworkspace, 4
bindd = ALT SHIFT, B, Move window to workspace 5, movetoworkspace, 5

bindd = ALT SHIFT, H, Swap window to the left, swapwindow, l
bindd = ALT SHIFT, L, Swap window to the right, swapwindow, r
bindd = ALT SHIFT, K, Swap window up, swapwindow, u
bindd = ALT SHIFT, J, Swap window down, swapwindow, d

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
# unbind = SUPER, SPACE
